/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ReturnResultProblem_H_
#define	_TCAP_ReturnResultProblem_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_ReturnResultProblem {
	TCAP_ReturnResultProblem_unrecognizedInvokeID	= 0,
	TCAP_ReturnResultProblem_returnResultUnexpected	= 1,
	TCAP_ReturnResultProblem_mistypedParameter	= 2
} e_TCAP_ReturnResultProblem;

/* TCAP_ReturnResultProblem */
typedef long	 TCAP_ReturnResultProblem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ReturnResultProblem;
asn_struct_free_f TCAP_ReturnResultProblem_free;
asn_struct_print_f TCAP_ReturnResultProblem_print;
asn_constr_check_f TCAP_ReturnResultProblem_constraint;
ber_type_decoder_f TCAP_ReturnResultProblem_decode_ber;
der_type_encoder_f TCAP_ReturnResultProblem_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ReturnResultProblem_H_ */
#include <osmocom/tcap/asn_internal.h>
