/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _TCAP_ASN_CONSTANT_H
#define _TCAP_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_TCAP_P_AbortCause (0)
#define max_val_TCAP_P_AbortCause (127)
#define min_val_TCAP_InvokeIdType (-128)
#define max_val_TCAP_InvokeIdType (127)


#ifdef __cplusplus
}
#endif

#endif /* _TCAP_ASN_CONSTANT_H */
