/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_DialoguePDU_H_
#define	_TCAP_DialoguePDU_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_AARQ-apdu.h>
#include <osmocom/tcap/TCAP_AARE-apdu.h>
#include <osmocom/tcap/TCAP_ABRT-apdu.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_DialoguePDU_PR {
	TCAP_DialoguePDU_PR_NOTHING,	/* No components present */
	TCAP_DialoguePDU_PR_dialogueRequest,
	TCAP_DialoguePDU_PR_dialogueResponse,
	TCAP_DialoguePDU_PR_dialogueAbort
} TCAP_DialoguePDU_PR;

/* TCAP_DialoguePDU */
typedef struct TCAP_DialoguePDU {
	TCAP_DialoguePDU_PR present;
	union TCAP_DialoguePDU_u {
		TCAP_AARQ_apdu_t	 dialogueRequest;
		TCAP_AARE_apdu_t	 dialogueResponse;
		TCAP_ABRT_apdu_t	 dialogueAbort;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_DialoguePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_DialoguePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_DialoguePDU_H_ */
#include <osmocom/tcap/asn_internal.h>
