/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_OPERATION_H_
#define	_TCAP_OPERATION_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>
#include <osmocom/tcap/OBJECT_IDENTIFIER.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_OPERATION_PR {
	TCAP_OPERATION_PR_NOTHING,	/* No components present */
	TCAP_OPERATION_PR_localValue,
	TCAP_OPERATION_PR_globalValue
} TCAP_OPERATION_PR;

/* TCAP_OPERATION */
typedef struct TCAP_OPERATION {
	TCAP_OPERATION_PR present;
	union TCAP_OPERATION_u {
		long	 localValue;
		OBJECT_IDENTIFIER_t	 globalValue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_OPERATION_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_OPERATION;
extern asn_CHOICE_specifics_t asn_SPC_TCAP_OPERATION_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_OPERATION_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_OPERATION_H_ */
#include <osmocom/tcap/asn_internal.h>
