/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ExternalPDU_H_
#define	_TCAP_ExternalPDU_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/OBJECT_IDENTIFIER.h>
#include <osmocom/tcap/TCAP_Dialog1.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_ExternalPDU */
typedef struct TCAP_ExternalPDU {
	OBJECT_IDENTIFIER_t	 oid;
	TCAP_Dialog1_t	 dialog;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ExternalPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ExternalPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ExternalPDU_H_ */
#include <osmocom/tcap/asn_internal.h>
