/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_InvokeProblem_H_
#define	_TCAP_InvokeProblem_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_InvokeProblem {
	TCAP_InvokeProblem_duplicateInvokeID	= 0,
	TCAP_InvokeProblem_unrecognizedOperation	= 1,
	TCAP_InvokeProblem_mistypedParameter	= 2,
	TCAP_InvokeProblem_resourceLimitation	= 3,
	TCAP_InvokeProblem_initiatingRelease	= 4,
	TCAP_InvokeProblem_unrecognizedLinkedID	= 5,
	TCAP_InvokeProblem_linkedResponseUnexpected	= 6,
	TCAP_InvokeProblem_unexpectedLinkedOperation	= 7
} e_TCAP_InvokeProblem;

/* TCAP_InvokeProblem */
typedef long	 TCAP_InvokeProblem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_InvokeProblem;
asn_struct_free_f TCAP_InvokeProblem_free;
asn_struct_print_f TCAP_InvokeProblem_print;
asn_constr_check_f TCAP_InvokeProblem_constraint;
ber_type_decoder_f TCAP_InvokeProblem_decode_ber;
der_type_encoder_f TCAP_InvokeProblem_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_InvokeProblem_H_ */
#include <osmocom/tcap/asn_internal.h>
