/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ErrorCode_H_
#define	_TCAP_ErrorCode_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_ErrorCode_PR {
	TCAP_ErrorCode_PR_NOTHING,	/* No components present */
	TCAP_ErrorCode_PR_nationaler,
	TCAP_ErrorCode_PR_privateer
} TCAP_ErrorCode_PR;

/* TCAP_ErrorCode */
typedef struct TCAP_ErrorCode {
	TCAP_ErrorCode_PR present;
	union TCAP_ErrorCode_u {
		long	 nationaler;
		long	 privateer;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ErrorCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ErrorCode;
extern asn_CHOICE_specifics_t asn_SPC_TCAP_ErrorCode_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_ErrorCode_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ErrorCode_H_ */
#include <osmocom/tcap/asn_internal.h>
