/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_DialoguePortion_H_
#define	_TCAP_DialoguePortion_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_EXTERNAL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_DialoguePortion */
typedef TCAP_EXTERNAL_t	 TCAP_DialoguePortion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_DialoguePortion;
asn_struct_free_f TCAP_DialoguePortion_free;
asn_struct_print_f TCAP_DialoguePortion_print;
asn_constr_check_f TCAP_DialoguePortion_constraint;
ber_type_decoder_f TCAP_DialoguePortion_decode_ber;
der_type_encoder_f TCAP_DialoguePortion_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_DialoguePortion_H_ */
#include <osmocom/tcap/asn_internal.h>
