/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ReturnError_H_
#define	_TCAP_ReturnError_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_InvokeIdType.h>
#include <osmocom/tcap/TCAP_ErrorCode.h>
#include <osmocom/tcap/TCAP_Parameter.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_ReturnError */
typedef struct TCAP_ReturnError {
	TCAP_InvokeIdType_t	 invokeID;
	TCAP_ErrorCode_t	 errorCode;
	TCAP_Parameter_t	*parameter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ReturnError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ReturnError;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_ReturnError_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_ReturnError_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ReturnError_H_ */
#include <osmocom/tcap/asn_internal.h>
