/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_ABRT_apdu_H_
#define	_TCAP_ABRT_apdu_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_ABRT-source.h>
#include <osmocom/tcap/asn_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TCAP_EXTERNAL;

/* TCAP_ABRT-apdu */
typedef struct TCAP_ABRT_apdu {
	TCAP_ABRT_source_t	 abort_source;
	struct TCAP_ABRT_apdu__user_information {
		A_SEQUENCE_OF(struct TCAP_EXTERNAL) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *user_information;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ABRT_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ABRT_apdu;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_ABRT_apdu_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_ABRT_apdu_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_EXTERNAL.h>

#endif	/* _TCAP_ABRT_apdu_H_ */
#include <osmocom/tcap/asn_internal.h>
