/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_GeneralProblem_H_
#define	_TCAP_GeneralProblem_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_GeneralProblem {
	TCAP_GeneralProblem_unrecognizedComponent	= 0,
	TCAP_GeneralProblem_mistypedComponent	= 1,
	TCAP_GeneralProblem_badlyStructuredComponent	= 2
} e_TCAP_GeneralProblem;

/* TCAP_GeneralProblem */
typedef long	 TCAP_GeneralProblem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_GeneralProblem;
asn_struct_free_f TCAP_GeneralProblem_free;
asn_struct_print_f TCAP_GeneralProblem_print;
asn_constr_check_f TCAP_GeneralProblem_constraint;
ber_type_decoder_f TCAP_GeneralProblem_decode_ber;
der_type_encoder_f TCAP_GeneralProblem_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_GeneralProblem_H_ */
#include <osmocom/tcap/asn_internal.h>
