/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ErrorCode_H_
#define	_TCAP_ErrorCode_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_ErrorCode */
typedef long	 TCAP_ErrorCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ErrorCode;
asn_struct_free_f TCAP_ErrorCode_free;
asn_struct_print_f TCAP_ErrorCode_print;
asn_constr_check_f TCAP_ErrorCode_constraint;
ber_type_decoder_f TCAP_ErrorCode_decode_ber;
der_type_encoder_f TCAP_ErrorCode_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ErrorCode_H_ */
#include <osmocom/tcap/asn_internal.h>
