/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_Reason_H_
#define	_TCAP_Reason_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_P-AbortCause.h>
#include <osmocom/tcap/TCAP_DialoguePortion.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_Reason_PR {
	TCAP_Reason_PR_NOTHING,	/* No components present */
	TCAP_Reason_PR_p_abortCause,
	TCAP_Reason_PR_u_abortCause
} TCAP_Reason_PR;

/* TCAP_Reason */
typedef struct TCAP_Reason {
	TCAP_Reason_PR present;
	union TCAP_Reason_u {
		TCAP_P_AbortCause_t	 p_abortCause;
		TCAP_DialoguePortion_t	 u_abortCause;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Reason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Reason;
extern asn_CHOICE_specifics_t asn_SPC_TCAP_Reason_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Reason_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_Reason_H_ */
#include <osmocom/tcap/asn_internal.h>
