/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_ABRT_source_H_
#define	_TCAP_ABRT_source_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_ABRT_source {
	TCAP_ABRT_source_dialogue_service_user	= 0,
	TCAP_ABRT_source_dialogue_service_provider	= 1
} e_TCAP_ABRT_source;

/* TCAP_ABRT-source */
typedef long	 TCAP_ABRT_source_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ABRT_source;
asn_struct_free_f TCAP_ABRT_source_free;
asn_struct_print_f TCAP_ABRT_source_print;
asn_constr_check_f TCAP_ABRT_source_constraint;
ber_type_decoder_f TCAP_ABRT_source_decode_ber;
der_type_encoder_f TCAP_ABRT_source_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ABRT_source_H_ */
#include <osmocom/tcap/asn_internal.h>
