/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_Invoke_H_
#define	_TCAP_Invoke_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_InvokeIdType.h>
#include <osmocom/tcap/TCAP_OPERATION.h>
#include <osmocom/tcap/TCAP_Parameter.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_Invoke */
typedef struct TCAP_Invoke {
	TCAP_InvokeIdType_t	 invokeID;
	TCAP_InvokeIdType_t	*linkedID;	/* OPTIONAL */
	TCAP_OPERATION_t	 opCode;
	TCAP_Parameter_t	*parameter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Invoke_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Invoke;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_Invoke_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Invoke_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_Invoke_H_ */
#include <osmocom/tcap/asn_internal.h>
