/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_InvokeIdType_H_
#define	_TCAP_InvokeIdType_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_InvokeIdType */
typedef long	 TCAP_InvokeIdType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_InvokeIdType;
asn_struct_free_f TCAP_InvokeIdType_free;
asn_struct_print_f TCAP_InvokeIdType_print;
asn_constr_check_f TCAP_InvokeIdType_constraint;
ber_type_decoder_f TCAP_InvokeIdType_decode_ber;
der_type_encoder_f TCAP_InvokeIdType_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_InvokeIdType_H_ */
#include <osmocom/tcap/asn_internal.h>
