/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_Unidirectional_H_
#define	_TCAP_Unidirectional_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_ComponentPortion.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TCAP_DialoguePortion;

/* TCAP_Unidirectional */
typedef struct TCAP_Unidirectional {
	struct TCAP_DialoguePortion	*dialoguePortion;	/* OPTIONAL */
	TCAP_ComponentPortion_t	 components;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Unidirectional_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Unidirectional;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_Unidirectional_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Unidirectional_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_DialoguePortion.h>

#endif	/* _TCAP_Unidirectional_H_ */
#include <osmocom/tcap/asn_internal.h>
