/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_Component_H_
#define	_TCAP_Component_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_Invoke.h>
#include <osmocom/tcap/TCAP_ReturnResult.h>
#include <osmocom/tcap/TCAP_ReturnError.h>
#include <osmocom/tcap/TCAP_Reject.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_Component_PR {
	TCAP_Component_PR_NOTHING,	/* No components present */
	TCAP_Component_PR_invoke,
	TCAP_Component_PR_returnResultLast,
	TCAP_Component_PR_returnError,
	TCAP_Component_PR_reject,
	TCAP_Component_PR_returnResultNotLast
} TCAP_Component_PR;

/* TCAP_Component */
typedef struct TCAP_Component {
	TCAP_Component_PR present;
	union TCAP_Component_u {
		TCAP_Invoke_t	 invoke;
		TCAP_ReturnResult_t	 returnResultLast;
		TCAP_ReturnError_t	 returnError;
		TCAP_Reject_t	 reject;
		TCAP_ReturnResult_t	 returnResultNotLast;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Component_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Component;
extern asn_CHOICE_specifics_t asn_SPC_TCAP_Component_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Component_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_Component_H_ */
#include <osmocom/tcap/asn_internal.h>
