/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_Continue_H_
#define	_TCAP_Continue_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_OrigTransactionID.h>
#include <osmocom/tcap/TCAP_DestTransactionID.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TCAP_DialoguePortion;
struct TCAP_ComponentPortion;

/* TCAP_Continue */
typedef struct TCAP_Continue {
	TCAP_OrigTransactionID_t	 otid;
	TCAP_DestTransactionID_t	 dtid;
	struct TCAP_DialoguePortion	*dialoguePortion;	/* OPTIONAL */
	struct TCAP_ComponentPortion	*components;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Continue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Continue;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_Continue_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Continue_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_DialoguePortion.h>
#include <osmocom/tcap/TCAP_ComponentPortion.h>

#endif	/* _TCAP_Continue_H_ */
#include <osmocom/tcap/asn_internal.h>
