/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ComponentPortion_H_
#define	_TCAP_ComponentPortion_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/asn_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TCAP_Component;

/* TCAP_ComponentPortion */
typedef struct TCAP_ComponentPortion {
	A_SEQUENCE_OF(struct TCAP_Component) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ComponentPortion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ComponentPortion;
extern asn_SET_OF_specifics_t asn_SPC_TCAP_ComponentPortion_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_ComponentPortion_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_Component.h>

#endif	/* _TCAP_ComponentPortion_H_ */
#include <osmocom/tcap/asn_internal.h>
