/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN1C-UsefulInformationObjectClasses"
 */

#ifndef	_TCAP_EXTERNAL_H_
#define	_TCAP_EXTERNAL_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/OBJECT_IDENTIFIER.h>
#include <osmocom/tcap/NativeInteger.h>
#include <osmocom/tcap/ObjectDescriptor.h>
#include <osmocom/tcap/ANY.h>
#include <osmocom/tcap/OCTET_STRING.h>
#include <osmocom/tcap/BIT_STRING.h>
#include <osmocom/tcap/constr_CHOICE.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_EXTERNAL__encoding_PR {
	TCAP_EXTERNAL__encoding_PR_NOTHING,	/* No components present */
	TCAP_EXTERNAL__encoding_PR_single_ASN1_type,
	TCAP_EXTERNAL__encoding_PR_octet_aligned,
	TCAP_EXTERNAL__encoding_PR_arbitrary
} TCAP_EXTERNAL__encoding_PR;

/* TCAP_EXTERNAL */
typedef struct TCAP_EXTERNAL {
	OBJECT_IDENTIFIER_t	*direct_reference;	/* OPTIONAL */
	long	*indirect_reference;	/* OPTIONAL */
	ObjectDescriptor_t	*data_value_descriptor;	/* OPTIONAL */
	struct TCAP_EXTERNAL__encoding {
		TCAP_EXTERNAL__encoding_PR present;
		union TCAP_EXTERNAL__TCAP_encoding_u {
			ANY_t	 single_ASN1_type;
			OCTET_STRING_t	 octet_aligned;
			BIT_STRING_t	 arbitrary;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} encoding;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_EXTERNAL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_EXTERNAL;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_EXTERNAL_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_EXTERNAL_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_EXTERNAL_H_ */
#include <osmocom/tcap/asn_internal.h>
