/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ReturnResult_H_
#define	_TCAP_ReturnResult_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_InvokeIdType.h>
#include <osmocom/tcap/TCAP_OPERATION.h>
#include <osmocom/tcap/TCAP_Parameter.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_ReturnResult */
typedef struct TCAP_ReturnResult {
	TCAP_InvokeIdType_t	 invokeID;
	struct TCAP_ReturnResult__resultretres {
		TCAP_OPERATION_t	 opCode;
		TCAP_Parameter_t	*parameter;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *resultretres;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ReturnResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ReturnResult;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_ReturnResult_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_ReturnResult_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ReturnResult_H_ */
#include <osmocom/tcap/asn_internal.h>
