/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ReturnErrorProblem_H_
#define	_TCAP_ReturnErrorProblem_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_ReturnErrorProblem {
	TCAP_ReturnErrorProblem_unrecognizedInvokeID	= 0,
	TCAP_ReturnErrorProblem_returnErrorUnexpected	= 1,
	TCAP_ReturnErrorProblem_unrecognizedError	= 2,
	TCAP_ReturnErrorProblem_unexpectedError	= 3,
	TCAP_ReturnErrorProblem_mistypedParameter	= 4
} e_TCAP_ReturnErrorProblem;

/* TCAP_ReturnErrorProblem */
typedef long	 TCAP_ReturnErrorProblem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ReturnErrorProblem;
asn_struct_free_f TCAP_ReturnErrorProblem_free;
asn_struct_print_f TCAP_ReturnErrorProblem_print;
asn_constr_check_f TCAP_ReturnErrorProblem_constraint;
ber_type_decoder_f TCAP_ReturnErrorProblem_decode_ber;
der_type_encoder_f TCAP_ReturnErrorProblem_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ReturnErrorProblem_H_ */
#include <osmocom/tcap/asn_internal.h>
