/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "UnidialoguePDUs"
 */

#ifndef	_TCAP_UniDialoguePDU_H_
#define	_TCAP_UniDialoguePDU_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_AUDT-apdu.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_UniDialoguePDU_PR {
	TCAP_UniDialoguePDU_PR_NOTHING,	/* No components present */
	TCAP_UniDialoguePDU_PR_unidialoguePDU
} TCAP_UniDialoguePDU_PR;

/* TCAP_UniDialoguePDU */
typedef struct TCAP_UniDialoguePDU {
	TCAP_UniDialoguePDU_PR present;
	union TCAP_UniDialoguePDU_u {
		TCAP_AUDT_apdu_t	 unidialoguePDU;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_UniDialoguePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_UniDialoguePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_UniDialoguePDU_H_ */
#include <osmocom/tcap/asn_internal.h>
