/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_P_AbortCause_H_
#define	_TCAP_P_AbortCause_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_P_AbortCause {
	TCAP_P_AbortCause_unrecognizedMessageType	= 0,
	TCAP_P_AbortCause_unrecognizedTransactionID	= 1,
	TCAP_P_AbortCause_badlyFormattedTransactionPortion	= 2,
	TCAP_P_AbortCause_incorrectTransactionPortion	= 3,
	TCAP_P_AbortCause_resourceLimitation	= 4
} e_TCAP_P_AbortCause;

/* TCAP_P-AbortCause */
typedef long	 TCAP_P_AbortCause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_P_AbortCause;
asn_struct_free_f TCAP_P_AbortCause_free;
asn_struct_print_f TCAP_P_AbortCause_print;
asn_constr_check_f TCAP_P_AbortCause_constraint;
ber_type_decoder_f TCAP_P_AbortCause_decode_ber;
der_type_encoder_f TCAP_P_AbortCause_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_P_AbortCause_H_ */
#include <osmocom/tcap/asn_internal.h>
