/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_ERROR_H_
#define	_TCAP_ERROR_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>
#include <osmocom/tcap/OBJECT_IDENTIFIER.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_ERROR_PR {
	TCAP_ERROR_PR_NOTHING,	/* No components present */
	TCAP_ERROR_PR_localValue,
	TCAP_ERROR_PR_globalValue
} TCAP_ERROR_PR;

/* TCAP_ERROR */
typedef struct TCAP_ERROR {
	TCAP_ERROR_PR present;
	union TCAP_ERROR_u {
		long	 localValue;
		OBJECT_IDENTIFIER_t	 globalValue;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_ERROR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_ERROR;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_ERROR_H_ */
#include <osmocom/tcap/asn_internal.h>
