/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_AARQ_apdu_H_
#define	_TCAP_AARQ_apdu_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/BIT_STRING.h>
#include <osmocom/tcap/OBJECT_IDENTIFIER.h>
#include <osmocom/tcap/asn_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_AARQ_apdu__protocol_version {
	TCAP_AARQ_apdu__protocol_version_version1	= 0
} e_TCAP_AARQ_apdu__protocol_version;

/* Forward declarations */
struct TCAP_EXTERNAL;

/* TCAP_AARQ-apdu */
typedef struct TCAP_AARQ_apdu {
	BIT_STRING_t	*protocol_version;	/* DEFAULT {version1} */
	OBJECT_IDENTIFIER_t	 application_context_name;
	struct TCAP_AARQ_apdu__user_information {
		A_SEQUENCE_OF(struct TCAP_EXTERNAL) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *user_information;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_AARQ_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_AARQ_apdu;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_AARQ_apdu_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_AARQ_apdu_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_EXTERNAL.h>

#endif	/* _TCAP_AARQ_apdu_H_ */
#include <osmocom/tcap/asn_internal.h>
