/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_DestTransactionID_H_
#define	_TCAP_DestTransactionID_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TCAP_DestTransactionID */
typedef OCTET_STRING_t	 TCAP_DestTransactionID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_DestTransactionID;
asn_struct_free_f TCAP_DestTransactionID_free;
asn_struct_print_f TCAP_DestTransactionID_print;
asn_constr_check_f TCAP_DestTransactionID_constraint;
ber_type_decoder_f TCAP_DestTransactionID_decode_ber;
der_type_encoder_f TCAP_DestTransactionID_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_DestTransactionID_H_ */
#include <osmocom/tcap/asn_internal.h>
