/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_RLRE_apdu_H_
#define	_TCAP_RLRE_apdu_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_Release-response-reason.h>
#include <osmocom/tcap/asn_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE_OF.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TCAP_EXTERNAL;

/* TCAP_RLRE-apdu */
typedef struct TCAP_RLRE_apdu {
	TCAP_Release_response_reason_t	*reason;	/* OPTIONAL */
	struct TCAP_RLRE_apdu__user_information {
		A_SEQUENCE_OF(struct TCAP_EXTERNAL) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *user_information;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_RLRE_apdu_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_RLRE_apdu;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_EXTERNAL.h>

#endif	/* _TCAP_RLRE_apdu_H_ */
#include <osmocom/tcap/asn_internal.h>
