/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TCAPMessages"
 */

#ifndef	_TCAP_Abort_H_
#define	_TCAP_Abort_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/TCAP_DestTransactionID.h>
#include <osmocom/tcap/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TCAP_Reason;

/* TCAP_Abort */
typedef struct TCAP_Abort {
	TCAP_DestTransactionID_t	 dtid;
	struct TCAP_Reason	*reason;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Abort_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Abort;
extern asn_SEQUENCE_specifics_t asn_SPC_TCAP_Abort_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Abort_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include <osmocom/tcap/TCAP_Reason.h>

#endif	/* _TCAP_Abort_H_ */
#include <osmocom/tcap/asn_internal.h>
