/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_Associate_source_diagnostic_H_
#define	_TCAP_Associate_source_diagnostic_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>
#include <osmocom/tcap/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_Associate_source_diagnostic_PR {
	TCAP_Associate_source_diagnostic_PR_NOTHING,	/* No components present */
	TCAP_Associate_source_diagnostic_PR_dialogue_service_user,
	TCAP_Associate_source_diagnostic_PR_dialogue_service_provider
} TCAP_Associate_source_diagnostic_PR;
typedef enum TCAP_Associate_source_diagnostic__dialogue_service_user {
	TCAP_Associate_source_diagnostic__dialogue_service_user_null	= 0,
	TCAP_Associate_source_diagnostic__dialogue_service_user_no_reason_given	= 1,
	TCAP_Associate_source_diagnostic__dialogue_service_user_application_context_name_not_supported	= 2
} e_TCAP_Associate_source_diagnostic__dialogue_service_user;
typedef enum TCAP_Associate_source_diagnostic__dialogue_service_provider {
	TCAP_Associate_source_diagnostic__dialogue_service_provider_null	= 0,
	TCAP_Associate_source_diagnostic__dialogue_service_provider_no_reason_given	= 1,
	TCAP_Associate_source_diagnostic__dialogue_service_provider_no_common_dialogue_portion	= 2
} e_TCAP_Associate_source_diagnostic__dialogue_service_provider;

/* TCAP_Associate-source-diagnostic */
typedef struct TCAP_Associate_source_diagnostic {
	TCAP_Associate_source_diagnostic_PR present;
	union TCAP_Associate_source_diagnostic_u {
		long	 dialogue_service_user;
		long	 dialogue_service_provider;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TCAP_Associate_source_diagnostic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Associate_source_diagnostic;
extern asn_CHOICE_specifics_t asn_SPC_TCAP_Associate_source_diagnostic_specs_1;
extern asn_TYPE_member_t asn_MBR_TCAP_Associate_source_diagnostic_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_Associate_source_diagnostic_H_ */
#include <osmocom/tcap/asn_internal.h>
