/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DialoguePDUs"
 */

#ifndef	_TCAP_Release_response_reason_H_
#define	_TCAP_Release_response_reason_H_


#include <osmocom/tcap/asn_application.h>

/* Including external dependencies */
#include <osmocom/tcap/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TCAP_Release_response_reason {
	TCAP_Release_response_reason_normal	= 0,
	TCAP_Release_response_reason_not_finished	= 1,
	TCAP_Release_response_reason_user_defined	= 30
} e_TCAP_Release_response_reason;

/* TCAP_Release-response-reason */
typedef long	 TCAP_Release_response_reason_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TCAP_Release_response_reason;
asn_struct_free_f TCAP_Release_response_reason_free;
asn_struct_print_f TCAP_Release_response_reason_print;
asn_constr_check_f TCAP_Release_response_reason_constraint;
ber_type_decoder_f TCAP_Release_response_reason_decode_ber;
der_type_encoder_f TCAP_Release_response_reason_encode_der;

#ifdef __cplusplus
}
#endif

#endif	/* _TCAP_Release_response_reason_H_ */
#include <osmocom/tcap/asn_internal.h>
